### PR TITLE
Update to CUDA 10.0

### PR DESCRIPTION
**Pull request by naetherm**
Updated DerelictCUDA for the CUDA 10.0 version.

### CODE REVIEW

**Review by p0nce — COMMENTED** [review]
I'm speaking about https://github.com/DerelictOrg/DerelictCUDA/pull/4/commits/2b2b4ff8ff1dd46f6315de13b786eea05b15f15c specifically.

Hello, this is not how Derelict works. You are supposed to add the most recent possible pathes before the most ancient ones, that way the project will still be able to load previous CUDA versions. I cannot make a tag until you've fixed this. Else it could break other people's projects.

**Comment by naetherm** [comment]
Hey p0nce, 

thanks for the note. I will take care about that on the weekend.

**Comment by p0nce** [comment]
Hello @naetherm 
DerelictCUDA is abandoned because I don't have time anymore to update it, would you like to be the maintainer of DerelictCUDA? It would make more sense than the one to "maintain" would be someone who actually needs it. :)

**Comment by naetherm** [comment]
Sorry for the late answer, got some more work to do. Of course, I could maintain the project.

**Pull request merged**
